//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Escuela_canina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matricula
    {
        public int cod_mat { get; set; }
        public Nullable<int> num_peluditos_mat { get; set; }
        public string razon_ingreso_mat { get; set; }
        public string extras_mat { get; set; }
    }
}
