//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Escuela_canina.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class escuela_caninaEntities : DbContext
    {
        public escuela_caninaEntities()
            : base("name=escuela_caninaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<matricula> matricula { get; set; }
        public virtual DbSet<papis> papis { get; set; }
        public virtual DbSet<peludos> peludos { get; set; }
        public virtual DbSet<profes> profes { get; set; }
    }
}
