//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Escuela_canina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class papis
    {
        public int tel_pap { get; set; }
        public string nom_pap { get; set; }
        public Nullable<System.DateTime> fch_ingreso_pap { get; set; }
    }
}
