//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Escuela_canina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peludos
    {
        public int cod_pel { get; set; }
        public string nom_pel { get; set; }
        public string tipo_trato_pel { get; set; }
        public string raza_pel { get; set; }
        public Nullable<int> tel_pap { get; set; }
    }
}
