//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Escuela_canina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profes
    {
        public int cod_profe { get; set; }
        public string nom_profe { get; set; }
        public string tipo_profe { get; set; }
        public Nullable<int> tel_profe { get; set; }
    }
}
